services:
  anjos-bolos-email-app:
    image: amazoncorretto:21
    container_name: anjos-bolos-email-app
    ports:
      - "8081:8081"
    volumes:
      - /usr/share/api-email:/app               # diretório com o JAR
      - /usr/share/api-email/.env:/app/.env     # mesmo .env que o CI/CD grava
    working_dir: /app
    command: java -jar email_service.jar
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - rabbitmq-email
    networks:
      - email-network
    restart: unless-stopped

  rabbitmq-email:
    image: rabbitmq:3.13-management
    container_name: anjos-bolos-rabbitmq-email
    environment:
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_USER=myuser
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_email_data:/var/lib/rabbitmq
    networks:
      - email-network
    restart: unless-stopped

volumes:
  rabbitmq_email_data:

networks:
  email-network:
    driver: bridge